version: '3'
#сервис это контейнер
services:
  server:
  #указывает путь до докерфайла
    build: .
    #проброс портов
    ports:
      - 6080:8090
    #если аварийно закончил работу, можно вооьще это убрать
    restart: always
